// Code generated by mockery v2.53.4. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	model "github.com/mattermost/mattermost/server/public/model"
	request "github.com/mattermost/mattermost/server/public/shared/request"
	mock "github.com/stretchr/testify/mock"
)

// ContentFlaggingStore is an autogenerated mock type for the ContentFlaggingStore type
type ContentFlaggingStore struct {
	mock.Mock
}

// ClearCaches provides a mock function with no fields
func (_m *ContentFlaggingStore) ClearCaches() {
	_m.Called()
}

// GetSettings provides a mock function with no fields
func (_m *ContentFlaggingStore) GetSettings() (*model.ContentFlaggingSettingsRequest, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSettings")
	}

	var r0 *model.ContentFlaggingSettingsRequest
	var r1 error
	if rf, ok := ret.Get(0).(func() (*model.ContentFlaggingSettingsRequest, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *model.ContentFlaggingSettingsRequest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ContentFlaggingSettingsRequest)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTrackedChannelIDs provides a mock function with given fields: rctx
func (_m *ContentFlaggingStore) GetTrackedChannelIDs(rctx request.CTX) ([]string, error) {
	ret := _m.Called(rctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTrackedChannelIDs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CTX) ([]string, error)); ok {
		return rf(rctx)
	}
	if rf, ok := ret.Get(0).(func(request.CTX) []string); ok {
		r0 = rf(rctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(request.CTX) error); ok {
		r1 = rf(rctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveSettings provides a mock function with given fields: config
func (_m *ContentFlaggingStore) SaveSettings(config model.ContentFlaggingSettingsRequest) error {
	ret := _m.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for SaveSettings")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.ContentFlaggingSettingsRequest) error); ok {
		r0 = rf(config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewContentFlaggingStore creates a new instance of ContentFlaggingStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContentFlaggingStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContentFlaggingStore {
	mock := &ContentFlaggingStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
