// Code generated by mockery v2.53.4. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	context "context"

	model "github.com/mattermost/mattermost/server/public/model"
	mock "github.com/stretchr/testify/mock"
)

// UserPostDeliveryContentReviewStore is an autogenerated mock type for the UserPostDeliveryContentReviewStore type
type UserPostDeliveryContentReviewStore struct {
	mock.Mock
}

// CountByPost provides a mock function with given fields: ctx, postID
func (_m *UserPostDeliveryContentReviewStore) CountByPost(ctx context.Context, postID string) (int64, error) {
	ret := _m.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for CountByPost")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, postID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, postID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteByPost provides a mock function with given fields: ctx, postID
func (_m *UserPostDeliveryContentReviewStore) DeleteByPost(ctx context.Context, postID string) error {
	ret := _m.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByPost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, postID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveBatch provides a mock function with given fields: ctx, records, jobID
func (_m *UserPostDeliveryContentReviewStore) SaveBatch(ctx context.Context, records []model.UserPostDelivery, jobID string) error {
	ret := _m.Called(ctx, records, jobID)

	if len(ret) == 0 {
		panic("no return value specified for SaveBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.UserPostDelivery, string) error); ok {
		r0 = rf(ctx, records, jobID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserPostDeliveryContentReviewStore creates a new instance of UserPostDeliveryContentReviewStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserPostDeliveryContentReviewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserPostDeliveryContentReviewStore {
	mock := &UserPostDeliveryContentReviewStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
