// Code generated by mockery v2.53.4. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	context "context"

	model "github.com/mattermost/mattermost/server/public/model"
	mock "github.com/stretchr/testify/mock"
)

// UserPostDeliveryContentReviewStore is an autogenerated mock type for the UserPostDeliveryContentReviewStore type
type UserPostDeliveryContentReviewStore struct {
	mock.Mock
}

// CountByReviewPost provides a mock function with given fields: ctx, reviewPostID
func (_m *UserPostDeliveryContentReviewStore) CountByReviewPost(ctx context.Context, reviewPostID string) (int64, error) {
	ret := _m.Called(ctx, reviewPostID)

	if len(ret) == 0 {
		panic("no return value specified for CountByReviewPost")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, reviewPostID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, reviewPostID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, reviewPostID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteByReviewPost provides a mock function with given fields: ctx, reviewPostID
func (_m *UserPostDeliveryContentReviewStore) DeleteByReviewPost(ctx context.Context, reviewPostID string) error {
	ret := _m.Called(ctx, reviewPostID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByReviewPost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, reviewPostID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByReviewPost provides a mock function with given fields: ctx, reviewPostID, after, limit
func (_m *UserPostDeliveryContentReviewStore) GetByReviewPost(ctx context.Context, reviewPostID string, after model.UserPostDeliveryReviewCursor, limit int) ([]model.UserPostDeliveryContentReview, error) {
	ret := _m.Called(ctx, reviewPostID, after, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetByReviewPost")
	}

	var r0 []model.UserPostDeliveryContentReview
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.UserPostDeliveryReviewCursor, int) ([]model.UserPostDeliveryContentReview, error)); ok {
		return rf(ctx, reviewPostID, after, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.UserPostDeliveryReviewCursor, int) []model.UserPostDeliveryContentReview); ok {
		r0 = rf(ctx, reviewPostID, after, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserPostDeliveryContentReview)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.UserPostDeliveryReviewCursor, int) error); ok {
		r1 = rf(ctx, reviewPostID, after, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveBatch provides a mock function with given fields: ctx, reviewPostID, records, jobID
func (_m *UserPostDeliveryContentReviewStore) SaveBatch(ctx context.Context, reviewPostID string, records []model.UserPostDelivery, jobID string) error {
	ret := _m.Called(ctx, reviewPostID, records, jobID)

	if len(ret) == 0 {
		panic("no return value specified for SaveBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []model.UserPostDelivery, string) error); ok {
		r0 = rf(ctx, reviewPostID, records, jobID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserPostDeliveryContentReviewStore creates a new instance of UserPostDeliveryContentReviewStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserPostDeliveryContentReviewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserPostDeliveryContentReviewStore {
	mock := &UserPostDeliveryContentReviewStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
